# Generated by Django 2.1.8 on 2019-06-19 02:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=128, null=True)),
                ('companyVAT', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('companyAddress', models.CharField(max_length=60, null=True)),
                ('companyZIP', models.CharField(max_length=12, null=True)),
                ('comapnyCity', models.CharField(max_length=60, null=True)),
                ('companyRating', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
